[package]
name = "n_choose_k"
version = "0.1.3"
license = "MIT"
edition = "2021"

[[bin]]
name = "n-choose-k"
path = "src/main.rs"

[[bin]]
name = "nck"
path = "src/main.rs"

[dependencies]
num = "0.4.0"
factorial = { path = "../factorial" }
clap = { version = "*", features = ["derive"] }
